version: 2
jobs:
  build:
    docker:
      - image: haskell:latest
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run: stack setup
      - run: stack build --fast
      - save_cache:
          key: cache
          paths:
            - ~/.stack
      - run: stack exec blog build
